[gcp_service_account]
type = "service_account"
project_id = "SEU_PROJECT_ID_AQUI"
private_key_id = "SUA_KEY_ID_AQUI"
private_key = "-----BEGIN PRIVATE KEY-----\nSUA_CHAVE_PRIVADA_AQUI\n-----END PRIVATE KEY-----\n"
client_email = "SEU_SERVICE_ACCOUNT_EMAIL@SEU_PROJETO.iam.gserviceaccount.com"
